FROM ubuntu:20.04

RUN apt-get update && apt-get install -y \
  net-tools \
  traceroute \
  iptables \
  iproute2 \
  arping \
  ipcalc \
  telnet \
  lsof  \
  ipvsadm \
  curl \
  dnsutils \
  wget \
  ethtool \
  tcpdump \
  && apt clean
