# k8s.gcr.io/etcd:3.4.13-0
# docker.io/wtxue/etcd:3.4.13-0
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  labels:
    app: etcd
    version: blue
spec:
  serviceName: etcd
  replicas: 3
  selector:
    matchLabels:
      app: etcd
      version: blue
  template:
    metadata:
      name: etcd
      labels:
        app: etcd
        version: blue
    spec:
      containers:
        - name: etcd
          image: docker.io/wtxue/etcd:3.4.13-0
          ports:
            - containerPort: 2379
              name: client
            - containerPort: 2380
              name: peer
          env:
            - name: INITIAL_CLUSTER_SIZE
              value: "3"
            - name: CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          #          resources:
          #            requests:
          #              cpu: 100m
          #              memory: 512Mi
          volumeMounts:
            - name: datadir
              mountPath: /var/run/etcd
          command:
            - /bin/sh
            - -c
            - |
              PEERS="etcd-0=http://etcd-0.etcd:2380,etcd-1=http://etcd-1.etcd:2380,etcd-2=http://etcd-2.etcd:2380"
              exec etcd --name ${HOSTNAME} \
                --listen-peer-urls http://0.0.0.0:2380 \
                --listen-client-urls http://0.0.0.0:2379 \
                --advertise-client-urls http://${HOSTNAME}.etcd:2379 \
                --initial-advertise-peer-urls http://${HOSTNAME}:2380 \
                --initial-cluster-token etcd-cluster-1 \
                --initial-cluster ${PEERS} \
                --initial-cluster-state new \
                --data-dir /var/run/etcd/default.etcd \
                --logger=zap
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
#        storageClassName: local-storage
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  labels:
    app: etcd
spec:
  ports:
    - port: 2380
      name: etcd-server
    - port: 2379
      name: etcd-client
  clusterIP: None
  selector:
    app: etcd
  publishNotReadyAddresses: true
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: etcd-pdb
  labels:
    pdb: etcd
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: etcd
---
