apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: ha-local-cluster
  name: ha-local-cluster
---
apiVersion: devops.k8s.io/v1
kind: Cluster
metadata:
  name: ha-local-cluster
  namespace: ha-local-cluster
  annotations:
#    "k8s.io/step.restore": "EnsurePreInstallHook"
    "k8s.io/local.dir": "bin/linux/"
    "k8s.io/apply.step": EnsureDeployCni, EnsureMetricsServer
#    "k8s.io/apiserver.vip": 172.16.18.17
spec:
  pause: false
  tenantID: k8s
  displayName: demo
  clusterType: baremetal
  osType: ubuntu
  criType: containerd
  version: v1.19.6
  networkDevice: ens34
  clusterCIDR: 172.16.101.0/24
  serviceCIDR: 172.16.201.0/24
  dnsDomain: cluster.local
  publicAlternativeNames:
    - ha-local.vip.k8s.io
  features:
    ipvs: true
    internalLB: true
    enableMasterSchedule: true
    ha:
      thirdParty:
        vip: "172.16.18.243"
        vport: 6443
    hooks:
      cniInstall: flannel
  properties:
    maxNodePodNum: 64
  machines:
    - ip: 172.16.18.17
      port: 22
      username: root
      password: "123456"
    - ip: 172.16.18.18
      port: 22
      username: root
      password: "123456"
    - ip: 172.16.18.19
      port: 22
      username: root
      password: "123456"
  apiServerExtraArgs:
    audit-log-maxage: "30"
    audit-log-maxbackup: "3"
    audit-log-maxsize: "100"
    audit-log-truncate-enabled: "true"
    audit-log-path: "/var/log/kubernetes/k8s-audit.log"
  controllerManagerExtraArgs:
    bind-address: "0.0.0.0"
  schedulerExtraArgs:
    bind-address: "0.0.0.0"
