apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: managed-cluster
  name: managed-cluster
---
apiVersion: devops.fake.io/v1
kind: Cluster
metadata:
  name: cc29pffvqtofq70ufrdb9
  namespace: managed-cluster
  annotations:
    "k8s.io/step.restore": EnsureExtKubeconfig
    "k8s.io/action": EnsureExtKubeconfig,EnsureAddons,EnsureFlannel
    "k8s.io/apiserver.vip": 172.16.0.101
spec:
  pause: false
  tenantID: wtxue
  displayName: demo
  clusterType: managed
  osType: ubuntu
  criType: containerd
  version: v1.20.4
  networkType: eth0
  clusterCIDR: 10.97.0.0/16
  serviceCIDR: 10.96.0.0/16
  dnsDomain: cluster.local
  publicAlternativeNames:
    - cc29pffvqtofq70ufrdb9.k8s.fake.io
  features:
    ipvs: true
    internalLB: true
    enableMasterSchedule: true
    ha:
      thirdParty:
        vip: "172.16.0.101"
        vport: 30443
    files:
      - src: "/k8s/bin/k9s"
        dst: "/usr/local/bin/k9s"
    hooks:
      PostCniInstall: flannel
  properties:
    maxNodePodNum: 64
  apiServerExtraArgs:
    audit-log-maxage: "30"
    audit-log-maxbackup: "3"
    audit-log-maxsize: "100"
    audit-log-truncate-enabled: "true"
    audit-policy-file: "/etc/kubernetes/audit-policy.yaml"
    audit-log-path: "/var/log/kubernetes/k8s-audit.log"
  controllerManagerExtraArgs:
    "bind-address": "0.0.0.0"
  schedulerExtraArgs:
    "bind-address": "0.0.0.0"
